/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ApiPublicCooudWebhookRouteImport } from './routes/api/public/cooud-webhook'
import { Route as ApiPublicCooudApiSplatRouteImport } from './routes/api/public/cooud-api/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCooudWebhookRoute = ApiPublicCooudWebhookRouteImport.update({
  id: '/api/public/cooud-webhook',
  path: '/api/public/cooud-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCooudApiSplatRoute = ApiPublicCooudApiSplatRouteImport.update({
  id: '/api/public/cooud-api/$',
  path: '/api/public/cooud-api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/cooud-webhook': typeof ApiPublicCooudWebhookRoute
  '/api/public/cooud-api/$': typeof ApiPublicCooudApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/cooud-webhook': typeof ApiPublicCooudWebhookRoute
  '/api/public/cooud-api/$': typeof ApiPublicCooudApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/api/public/cooud-webhook': typeof ApiPublicCooudWebhookRoute
  '/api/public/cooud-api/$': typeof ApiPublicCooudApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/checkout' | '/api/public/cooud-webhook' | '/api/public/cooud-api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/checkout' | '/api/public/cooud-webhook' | '/api/public/cooud-api/$'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/api/public/cooud-webhook'
    | '/api/public/cooud-api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiPublicCooudWebhookRoute: typeof ApiPublicCooudWebhookRoute
  ApiPublicCooudApiSplatRoute: typeof ApiPublicCooudApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cooud-webhook': {
      id: '/api/public/cooud-webhook'
      path: '/api/public/cooud-webhook'
      fullPath: '/api/public/cooud-webhook'
      preLoaderRoute: typeof ApiPublicCooudWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cooud-api/$': {
      id: '/api/public/cooud-api/$'
      path: '/api/public/cooud-api/$'
      fullPath: '/api/public/cooud-api/$'
      preLoaderRoute: typeof ApiPublicCooudApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ApiPublicCooudWebhookRoute: ApiPublicCooudWebhookRoute,
  ApiPublicCooudApiSplatRoute: ApiPublicCooudApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
